# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
  debug: true

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
# logs:
#    custom_components.enocean_cust: debug

binary_sensor:
- platform: enocean_cust
  id:
  - 254
  - 221
  - 223
  - 115